### PR TITLE
support for v3 iterm applescript dictionary changes

### PR DESCRIPTION
**Pull request by joshuacronemeyer**
Hi, I know there is already a pull request to fix this issue: https://github.com/skwp/vim-iterm-rspec/pull/5/ but I felt like a major drawback of that approach was having the hash of supported versions and having to set configuration. Seems better for the code to make the decision since we can just ask iterm its version. Also i found the parameterized version of the applescript harder to read and potentially limiting. So here is yet another pull request (yapr?)

### CODE REVIEW

**Comment by joshuacronemeyer** [comment]
BTW, it would be great to understand why you do that error handling/try again. I was guessing it was about handling scenario where the user quits iterm and runs specs, but that wasn't it. iterm fires right up without causing an error. I could never trigger that branch of the code and had to test it via a different means, however it doesn't seem necessary. Maybe we can simplify it? Or if not try to handle a specific error instead of all errors?

**Comment by ernestonakamura** [comment]
Your patch worked. Thank you.

**Comment by joshuacronemeyer** [comment]
Hey just checking in with this pull request. It has been a month. Would be great to get this merged and pulled into yadr if there are no issues with it. Thanks!

**Comment by skwp** [comment]
Sorry I didn't see this!

**Pull request merged**
